// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC40bWNcPdaPzvC-HI52THXZhkZdA_q_G8',
    appId: '1:289348261037:web:d7886281d8f1f9c54e6224',
    messagingSenderId: '289348261037',
    projectId: 'asambe-b2f41',
    authDomain: 'asambe-b2f41.firebaseapp.com',
    storageBucket: 'asambe-b2f41.appspot.com',
    measurementId: 'G-EE8VJ9B6QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjhS4nmTdDRi3UTQrtfCCxFVJBCewMRVk',
    appId: '1:289348261037:android:e51eb1a866a032344e6224',
    messagingSenderId: '289348261037',
    projectId: 'asambe-b2f41',
    storageBucket: 'asambe-b2f41.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSptq4tTLJ6C0nwet_jzzp0qAVXYQxEp8',
    appId: '1:289348261037:ios:cb0dbe551e0d689d4e6224',
    messagingSenderId: '289348261037',
    projectId: 'asambe-b2f41',
    storageBucket: 'asambe-b2f41.appspot.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSptq4tTLJ6C0nwet_jzzp0qAVXYQxEp8',
    appId: '1:289348261037:ios:cb0dbe551e0d689d4e6224',
    messagingSenderId: '289348261037',
    projectId: 'asambe-b2f41',
    storageBucket: 'asambe-b2f41.appspot.com',
    iosBundleId: 'za.co.wethinkcode.widgetsApp',
  );
}
